# Generated by Django 4.0.1 on 2022-02-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('about_me', models.CharField(max_length=200, verbose_name='about_me')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('gmail', models.CharField(max_length=100, null=True, verbose_name='Gmail')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('knowledge', models.CharField(max_length=200, verbose_name='knowledge')),
                ('skills', models.CharField(max_length=100, verbose_name='skills')),
                ('instagram', models.CharField(max_length=20, verbose_name='instagram')),
                ('time', models.FloatField(default=1644066088.263585)),
            ],
        ),
    ]
