# Generated by Django 4.0.1 on 2022-02-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.FloatField(default=1645116829.060086),
        ),
    ]
