# Generated by Django 4.0.1 on 2022-02-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='skills',
            field=models.JSONField(default=list, verbose_name='skills'),
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.FloatField(default=1645473129.388161),
        ),
    ]
