# Generated by Django 4.0.1 on 2022-02-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_data_skills_alter_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.FloatField(default=1645628606.931446),
        ),
    ]
